module.exports = {
  extends: ['@commitlint/config-conventional'],
  // 以下时我们自定义的规则
  types: [
    { value: 'feat', name: 'feat:     新增功能' },
    { value: 'build', name: 'build:    打包发布' },
    { value: 'css', name: 'css:      修改样式' },
    { value: 'update', name: 'update:   功能优化' },
    { value: 'fix', name: 'fix:      修复Bug' },
    { value: 'utils', name: 'utils:    工具方法' },
    { value: 'merge', name: 'merge:    合并代码' },
    { value: 'docs', name: 'docs:     文档变更' },
    { value: 'refactor', name: 'refactor: 代码重构', },
    { value: 'perf', name: 'perf:     改善性能', },
    { value: 'test', name: 'test:     测试用例' },
    { value: 'revert', name: 'revert:   代码回退' },
    { value: 'style', name: 'style:    代码格式', },
    { value: 'chore', name: 'chore:    变更项目构建或外部依赖', },
    { value: 'WIP', name: 'WIP:      正在施工' },
    { value: 'modules', name: 'modules:  依赖更新' },
  ],
  messages: {
    type: "选择提交的类型：",
    customScope: '输入提交影响的范围，如某个模块、功能或组件(可选)：',
    subject: '输入简短的描述：',
    body: '输入详细的描述，用"|"换行(可选)：',
    breaking: '当前版本与上个版本不兼容的地方(可选)：',
    footer: '此次提交修复的缺陷，如：#31, #34(可选)',
    confirmCommit: '确认提交？',
  },
  allowCustomScopes: true,
  skipQuestions: ['body', 'breaking', 'footer'],
  subjectLimit: 100,
}
